### ISSUE TITLE
Metastore result doesn't include some of datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/metastore#36]
@anuveyatsu said in gitter:

> @zelima I was looking at problem reported in the datahubio chat and noticed that metastore not returning correct response - https://api.datahub.io/metastore/search?datahub.ownerid=%223499e2dbfda832ee6cfbb28bddc1c4c7%22 - you can see only 2 datasets in this response, however, in the database I’ve found more than 10 `published` datasets..

## Acceptance criteria

* [x] metastore returns correct number of published datasets

## Tasks

* [x] investigate the problem

**Comment by zelima** [comment]
FIXED. The issue was related to specstore. It was not exporting metadata to metastore. For now reason is unknown for me as I could not replace locally, Indeed I restarted spec store service and now it seems to be working fine. In order to get alerts if this repeats https://github.com/datahq/datahub-health/issues/1
